baseURL = "https://lantanomads.com/"
languageCode = "en-us"
title = "Lanta Nomads"
enableGitInfo = true

disableKinds = ["taxonomy"]

[sitemap]
  changefreq = "monthly"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Information for remote workers coming to Koh Lanta, Thailand"
